# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data')),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
