# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import pollution_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=pollution_map.models.OverwriteStorage(), upload_to=b''),
        ),
    ]
