# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_map', '0002_auto_20180701_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('numClicks', models.IntegerField()),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
